# Generated by Django 4.2.2 on 2023-12-18 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id_book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='book_format',
            field=models.CharField(default='Hard Cover', max_length=25),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.SmallIntegerField(default=0),
        ),
    ]
